import './globals.css';
import Theme from './theme-provider.jsx';
import Providers from './provider';

export const metadata = {
  title: 'NFT Marketplace',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <body>
      <Theme>
        <Providers>
          {children}
        </Providers>
      </Theme>
    </body>
  </html>
);
export default RootLayout;
