import './globals.css';
import type { Metadata } from 'next';

import ThemeProviderWrapper from '@/app/theme-provider';
import { Providers } from '@/app/providers';
import React from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default ({
  children,
}: {
  children: React.ReactNode
}) => (
  <html lang="en">
    <body>
      <ThemeProviderWrapper>
        <Providers>
          {children}
        </Providers>
      </ThemeProviderWrapper>
    </body>
  </html>
);
