import './globals.css'
import type { Metadata } from 'next'

import ThemeProviderWrapper from "@/app/theme-provider";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <ThemeProviderWrapper>
        {children}
      </ThemeProviderWrapper>
      </body>
    </html>
  )
}
