import './globals.css';
import Theme from './theme-provider.jsx';

export const metadata = {
  title: 'NFT Marketplace',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <body>
      <Theme>
        {children}
      </Theme>
    </body>
  </html>
);
export default RootLayout;
